version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: thyroid_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - thyroid-network

  backend:
    build: ./backend
    container_name: thyroid_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/thyroid_db
      - AI_SERVICE_URL=http://ai-service-1:8000
      - AI_SERVICE_URL_2=http://ai-service-2:8000
    depends_on:
      - mongodb
      - ai-service-1
      - ai-service-2
    networks:
      - thyroid-network

  ai-service-1:
    build: ./ai-service-1
    container_name: thyroid_ai_1
    ports:
      - "8004:8000"
    networks:
      - thyroid-network

  ai-service-2:
    build: ./ai-service-2
    container_name: thyroid_ai_2
    ports:
      - "8001:8000"
    networks:
      - thyroid-network

  frontend:
    build: ./frontend
    container_name: thyroid_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - thyroid-network

networks:
  thyroid-network:
    driver: bridge

volumes:
  mongo_data:
